image: node:latest

stages:
- publish

before_script:
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc

publish-core:
  stage: publish
  only:
    - tags
  script:
    - npm publish --access public ./

publish-asset-analyzer:
  stage: publish
  only:
    - tags
  script:
    - npm publish --access public ./Scripts/Editor/Analyzers/Asset/

publish-asset-analyzer-rules:
  stage: publish
  only:
    - tags
  script:
    - npm publish --access public ./Scripts/Editor/Analyzers/Asset.RecommendedRules/