image: node:latest

stages:
- publish

before_script:
  - npm install -g npm-login-cmd
  - npx npm-login-cmd

publish-core:
  stage: publish
  only:
    - tags
  script:
    - npm publish --access public ./

publish-asset-analyzer:
  stage: publish
  only:
    - tags
  script:
    - npm publish --access public ./Scripts/Editor/Analyzers/Asset/

publish-asset-analyzer-rules:
  stage: publish
  only:
    - tags
  script:
    - npm publish --access public ./Scripts/Editor/Analyzers/Asset.RecommendedRules/